package com.pinetree408.research.autoswitchinglsi.exp.tasklist;

public class ExpFourTaskList {

    public static String[] p0 = {
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
    };

    public static String[] p1 = {
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
    };

    public static String[] p2 = {
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
    };

    public static String[] p3 = {
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
    };

    public static String[] p4 = {
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
    };

    public static String[] p5 = {
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
    };

    public static String[] p6 = {
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 3-ALSI",
    };

    public static String[] p7 = {
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
    };

    public static String[] p8 = {
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
    };

    public static String[] p9 = {
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
    };

    public static String[] p10 = {
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 1-ALSI",
            "person, 240, 2-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 1-ALSI",
            "person, 60, 2-ALSI",
    };

    public static String[] p11 = {
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
    };

    public static String[] p12 = {
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
            "person, 240, 3-ALSI",
            "person, 240, 2-ALSI",
            "person, 240, 1-ALSI",
            "person, 60, 3-ALSI",
            "person, 60, 2-ALSI",
            "person, 60, 1-ALSI",
    };
}
