package com.pinetree408.research.watchtapboard;

/**
 * Created by leesangyoon on 2017. 8. 15..
 */

public class Source {
    public static String[] name = {
            "camden",
            "alexander",
            "bryson",
            "austin",
            "ryan",
            "leonardo",
            "caleb",
            "nathaniel",
            "luca",
            "isaac",
            "david",
            "xavier",
            "eric",
            "bryce",
            "isaiah",
            "jayden",
            "patrick",
            "carter",
            "braxton",
            "jace",
            "jesus",
            "anthony",
            "alejandro",
            "mason",
            "samuel",
            "richard",
            "harrison",
            "hayden",
            "eli",
            "luis",
            "blake",
            "declan",
            "jaxson",
            "noah",
            "hudson",
            "josiah",
            "bradley",
            "jonah",
            "steven",
            "jose",
            "silas",
            "luke",
            "joseph",
            "santiago",
            "ashton",
            "evan",
            "julian",
            "gavin",
            "connor",
            "maddox",
            "abel",
            "greyson",
            "jordan",
            "axel",
            "grayson",
            "jason",
            "antonio",
            "sebastian",
            "micah",
            "cole",
            "daniel",
            "diego",
            "everett",
            "owen",
            "ezra",
            "elijah",
            "easton",
            "dylan",
            "landon",
            "cooper",
            "bennett",
            "asher",
            "jayce",
            "dominic",
            "george",
            "zachary",
            "jonathan",
            "emmanuel",
            "maxwell",
            "roman",
            "hunter",
            "theodore",
            "gabriel",
            "james",
            "kaiden",
            "maverick",
            "brayden",
            "jacob",
            "joshua",
            "miles",
            "aiden",
            "nolan",
            "elias",
            "carson",
            "parker",
            "max",
            "matthew",
            "adrian",
            "juan",
            "nathan",
            "ivan",
            "sawyer",
            "ryder",
            "jaxon",
            "damian",
            "levi",
            "christian",
            "mateo",
            "alex",
            "adam",
            "colton",
            "lucas",
            "brandon",
            "andrew",
            "oliver",
            "ryker",
            "leo",
            "abraham",
            "cameron",
            "jameson",
            "tyler",
            "chase",
            "aaron",
            "emmett",
            "william",
            "jack",
            "ethan",
            "michael",
            "charles",
            "timothy",
            "malachi",
            "ayden",
            "kingston",
            "wesley",
            "logan",
            "jude",
            "tristan",
            "carlos",
            "wyatt",
            "jeremiah",
            "bentley",
            "thomas",
            "brody",
            "nicholas",
            "preston",
            "john",
            "kevin",
            "weston",
            "justin",
            "ezekiel",
            "river",
            "brian",
            "messiah",
            "phoenix",
            "emanuel",
            "gunner",
            "beckett",
            "king",
            "muhammad",
            "jaden",
            "jesse",
            "adriel",
            "caden",
            "devin",
            "kendrick",
            "august",
            "sullivan",
            "shane",
            "kenneth",
            "stephen",
            "reid",
            "roberto",
            "kyle",
            "brooks",
            "finnegan",
            "paul",
            "gregory",
            "travis",
            "beckham",
            "corbin",
            "martin",
            "zane",
            "donovan",
            "erick",
            "jax",
            "andre",
            "gael",
            "jeremy",
            "peyton",
            "ali",
            "louis",
            "dallas",
            "charlie",
            "anderson",
            "kameron",
            "jaiden",
            "jeffrey",
            "finn",
            "ricardo",
            "cristian",
            "derek",
            "joel",
            "josue",
            "israel",
            "felix",
            "tanner",
            "waylon",
            "paxton",
            "edwin",
            "holden",
            "sean",
            "arthur",
            "dean",
            "angelo",
            "cesar",
            "iker",
            "mario",
            "rylan",
            "bryan",
            "omar",
            "victor",
            "rafael",
            "jayceon",
            "amari",
            "desmond",
            "ruby",
            "melanie",
            "vivian",
            "leah",
            "stella",
            "kellen",
            "kaitlyn",
            "naomi",
            "mila",
            "nora",
            "valentina",
            "adalynn",
            "jasmine",
            "brycen",
            "nasir",
            "emma",
            "valeria",
            "zoey",
            "chloe",
            "deacon",
            "ahmed",
            "juliana",
            "violet",
            "chris",
            "lennox",
            "claire",
            "nico",
            "keaton",
            "alexa",
            "raelynn",
            "mya",
            "omari",
            "layla",
            "presley",
            "skylar",
            "madelyn",
            "eva",
            "moises",
            "benson",
            "kian",
            "madeline",
            "kimberly",
            "conor",
            "isabelle",
            "reagan",
            "natalia",
            "brielle",
            "camila",
            "alyssa",
            "hannah",
            "nevaeh",
            "vivienne",
            "annabelle",
            "angelina",
            "kane",
            "valerie",
            "bodhi",
            "julianna",
            "faith",
            "mathew",
            "khloe",
            "eden",
            "kaylee",
            "ivy",
            "moses",
            "lydia",
            "khalil",
            "hailey",
            "jaime",
            "kinsley",
            "ellie",
            "leilani",
            "ronin",
            "juliette",
            "eleanor",
            "zayne",
            "matias",
            "anna",
            "ryleigh",
            "adriana",
            "zoe",
            "aria",
            "dennis",
            "jocelyn",
            "hugo",
            "saul",
            "vivienne",
            "trinity",
            "juliette",
            "margaret",
            "lydia",
            "piper",
            "adeline",
            "harmony",
            "darius",
            "kieran",
            "dustin",
            "ariana",
            "ella",
            "arjun",
            "bella",
            "michelle",
            "harper",
            "atlas",
            "aubrey",
            "arlo",
            "elena",
            "genesis",
            "taylor",
            "sophia",
            "grace",
            "autumn",
            "julia",
            "vanessa",
            "aubree",
            "liliana",
            "gianna",
            "raul",
            "mya",
            "aurora",
            "landyn",
            "maya",
            "kendall",
            "cyrus",
            "makayla",
            "ashley",
            "raiden",
            "lily",
            "mckenzie",
            "sarah",
            "alexandra",
            "cecilia",
            "arabella",
            "destiny",
            "clara",
            "hazel",
            "brooklynn",
            "brianna",
            "makenzie",
            "davis",
            "lucy",
            "ryland",
            "pierce",
            "emily",
            "rebecca",
            "maria",
            "amelia",
            "alijah",
            "kayla",
            "sadie",
            "aniyah",
            "melody",
            "adelaide",
            "maggie",
            "willow",
            "daisy",
            "iris",
            "cadence",
            "kali",
            "katelyn",
            "paislee",
            "marley",
            "london",
            "gabriela",
            "paris",
            "ruth",
            "bailey",
            "molly",
            "rose",
            "june",
            "noelle",
            "brynlee",
            "lauren",
            "mariana",
            "amy",
            "katie",
            "olive",
            "gabrielle",
            "mikayla",
            "amaya",
            "jade",
            "ximena",
            "teagan",
            "adelynn",
            "lilly",
            "laura",
            "kaydence",
            "jessica",
            "athena",
            "ada",
            "kylee",
            "haley",
            "kayleigh",
            "lilah",
            "aliyah",
            "lucille",
            "giselle",
            "nova",
            "lena",
            "miranda",
            "cassidy",
            "juliet",
            "lilliana",
            "leila",
            "ariel",
            "jenna",
            "reese",
            "eliana",
            "alaina",
            "adrianna",
            "genevieve",
            "ainsley",
            "kenzie",
            "hadley",
            "cheyenne",
            "nicole",
            "daleyza",
            "emilia",
            "luna",
            "hope",
            "sophie",
            "lola",
            "georgia",
            "norah",
            "laila",
            "lawson",
            "finley",
            "troy",
            "corey",
            "danny",
            "trevor",
            "ronald",
            "andy",
            "theo",
            "malcolm",
            "jensen",
            "marco",
            "drake",
            "skyler",
            "elizabeth",
            "charlotte",
            "porter",
            "jared",
            "landen",
            "brooklyn",
            "reed",
            "enzo",
            "milan",
            "cruz",
            "julio",
            "hendrix",
            "warren",
            "katherine",
            "colt",
            "quentin",
            "cason",
            "augustus",
            "walter",
            "major",
            "dakota",
            "dillon",
            "gabriella",
            "isabella",
            "royal",
            "mackenzie",
            "jayson",
            "gideon",
            "albert",
            "cade",
            "ari",
            "madison",
            "sterling",
            "penelope",
            "ibrahim",
            "kellan",
            "thiago",
            "arianna",
            "kayson",
            "zaiden",
            "kasen",
            "colby",
            "hector",
            "serenity",
            "drew",
            "legend",
            "damon",
            "braden",
            "prince",
            "gerardo",
            "allen",
            "kade",
            "ruben",
            "frank",
            "kennedy",
            "victoria",
            "caroline",
            "tate",
            "ellis",
            "samantha",
            "shawn",
            "abram",
            "walker",
            "ace",
            "mohammed",
            "tobias",
            "julius",
            "grady",
            "scott",
            "natalie",
            "quinn",
            "russell",
            "paisley",
            "keith",
            "leland",
            "jamison",
            "kolton",
            "sergio",
            "rodrigo",
            "ronan",
            "edgar",
            "bruce",
            "donald",
            "braylon",
            "esteban",
            "johnny",
            "leon",
            "mia",
            "rocco",
            "fabian",
            "francis",
            "romeo",
            "pablo",
            "addison",
            "dante",
            "lillian",
            "nash",
            "dexter",
            "brock",
            "scarlett",
            "emilio",
            "orion",
            "ismael",
            "solomon",
            "lane",
            "derrick",
            "kash",
            "aaliyah",
            "alexis",
            "marcos",
            "philip",
            "jonas",
            "leonel",
            "kyrie",
            "malik",
            "brennan",
            "savannah",
            "jaylen",
            "harvey",
            "gunnar",
            "rory",
            "daxton",
            "nikolai",
            "mohamed",
            "noel",
            "lawrence",
            "adan",
            "abigail",
            "kason",
            "braylen",
            "jaxton",
            "kamden",
            "armando",
            "jett",
            "enrique",
            "allison",
            "fernando",
            "tucker",
            "keegan",
            "conner",
            "joaquin",
            "kaden",
            "oscar",
            "cody",
            "karter",
            "calvin",
            "lukas",
            "brady",
            "tyson",
            "chance",
            "cash",
            "kai",
            "jasper",
            "killian",
            "elliott",
            "rhett",
            "jase",
            "emiliano",
            "nicolas",
            "edward",
            "collin",
            "graham",
            "mark",
            "marcus",
            "kaleb",
            "judah",
            "titus",
            "nehemiah",
            "rowan",
            "franklin",
            "archer",
            "matteo",
            "gage",
            "cayden",
            "emerson",
            "garrett",
            "karson",
            "remington",
            "colin",
            "lorenzo",
            "peter",
            "amir",
            "myles",
            "avery",
            "barrett",
            "maximus",
            "kyler",
            "johnathan",
            "marshall",
            "riley",
            "andres",
            "jorge",
            "zayden",
            "manuel",
            "spencer",
            "zachariah",
            "francisco",
            "eduardo",
            "grant",
            "elliot",
            "jake",
            "dominick",
            "javier",
            "miguel",
            "griffin",
            "beau",
            "atticus",
            "alan",
            "aidan",
            "caiden",
            "jay",
            "willow",
            "raegan",
            "kathryn",
            "callie",
            "elliana",
            "addilyn",
            "jordyn",
            "fiona",
            "alayna",
            "catalina",
            "jane",
            "sara",
            "ana",
            "maci",
            "amina",
            "malia",
            "isabel",
            "alana",
            "kayleigh",
            "annie",
            "londyn",
            "anastasia",
            "sabrina",
            "sienna",
            "adalyn",
            "andrea",
            "lila",
            "makenna",
            "kate",
            "maddison",
            "arielle",
            "charlee",
            "delaney",
            "gracie",
            "sydney",
            "lilah",
            "alivia",
            "rosalie",
            "allie",
            "adelyn",
            "cora",
            "blakely",
            "jennifer",
            "esther",
            "emery",
            "mckenna",
            "ayla",
            "lyla",
            "isla",
            "journey",
            "lucia",
            "norah",
            "summer",
            "melissa",
            "chelsea",
            "danielle",
            "mary",
            "eloise",
            "catherine",
            "rylee",
            "gracelyn",
            "diana",
            "gemma",
            "tessa",
            "arya",
            "rachel",
            "alina",
            "kinley",
            "mariah",
            "lia",
            "paige",
            "payton",
            "brooke",
            "keira",
            "camille",
            "jazmine",
            "alexia",
            "leslie",
            "holly",
            "helen",
            "aspen",
            "phoebe",
            "megan",
            "jillian",
            "leighton",
            "vera",
            "cataleya",
            "heidi",
            "juniper",
            "remi",
            "scarlet",
            "elsa",
            "harlow",
            "kyleigh",
            "veronica",
            "mallory",
            "nina",
            "karla",
            "amanda",
            "nayeli",
            "zara",
            "itzel",
            "ashlynn",
            "sarai",
            "carolina",
            "yaretzi",
            "raven",
            "addyson",
            "serena",
            "ariella",
            "kennedi",
            "lexi",
            "elisa",
            "kamryn",
            "julie",
            "adaline",
            "sierra",
            "macie",
            "alicia",
            "emmalyn",
            "joy",
            "averie",
            "kiara",
            "marilyn",
            "nadia",
            "daphne",
            "emersyn",
            "eve",
            "kamila",
            "skye",
            "annabella",
            "sloane",
            "thea",
            "jazmin",
            "millie",
            "jada",
            "abby",
            "briana",
            "selena",
            "madeleine",
            "elsie",
            "bristol",
            "hattie",
            "raelyn",
            "nylah",
            "ashlyn",
            "elaina",
            "kelly",
            "aylin",
            "lana",
            "kassidy",
            "viviana",
            "carmen",
            "sage",
            "rylie",
            "ember",
            "kaia",
            "macy",
            "braelyn",
            "miracle",
            "shelby",
            "freya",
            "karen",
            "bethany",
            "jaylah",
            "anaya",
            "kendra",
            "justice",
            "kyra",
            "amber",
            "kyla",
            "baylee",
            "christina",
            "gracelynn",
            "aisha",
            "haylee",
            "leia",
            "haven",
            "journee",
            "sylvia",
            "jazmin",
            "bianca",
            "jayda",
            "selah",
            "kelsey",
            "amira",
            "dahlia",
            "aubrie",
            "allyson",
            "gia",
            "amara",
            "marlee",
            "myla",
            "willa",
            "fatima",
            "joanna",
            "brittany",
            "jimena",
            "nyla",
            "amiyah",
            "aleena",
            "felicity",
            "emely",
            "brylee",
            "camilla",
            "lacey",
            "april",
            "elle",
            "maeve",
            "nia",
            "aleah",
            "erin",
            "luciana",
            "brinley",
            "zuri",
            "annalise",
            "melany",
            "mckinley",
            "miriam",
            "camryn",
            "briella",
            "maliyah",
            "alison",
            "jillian",
            "evelynn"
    };

    public static String[] app ={
            "flip master",
            "wish",
            "bitmoji",
            "snapchat",
            "angry birds match",
            "messenger",
            "instagram",
            "go music",
            "netflix",
            "noaa weather radar",
            "letgo",
            "s photo editor",
            "roblox",
            "dfndr security",
            "word connect",
            "spotify music",
            "pandora music",
            "pinterest",
            "uber",
            "amazon prime video",
            "snake vs block",
            "facebook",
            "offerup",
            "flippy knife",
            "starz",
            "espn fantasy sports",
            "word cookies",
            "whatsapp messenger",
            "my boost",
            "cm launcher threed five",
            "gasbuddy",
            "draftkings",
            "google play games",
            "final fantasy xv",
            "waze",
            "super mario run",
            "the weather channel",
            "amazon shopping",
            "topbuzz video",
            "bowmasters",
            "marco polo video walkie talkie",
            "espn",
            "magic tiles three",
            "flashlight",
            "subway surfers",
            "slither",
            "youtube music",
            "zello ptt walkie talkie",
            "lyft",
            "musical",
            "soundcloud",
            "textnow",
            "spinner boost",
            "last day on earth",
            "flipagram",
            "tubi tv",
            "golf clash",
            "remind",
            "roll the ball",
            "yahoo fantasy sports",
            "eight ball pool",
            "topbuzz",
            "walmart",
            "block craft threed",
            "hulu",
            "madden nfl football",
            "classdojo",
            "choices",
            "my photo editor",
            "power security",
            "google duo",
            "super",
            "draft",
            "fantasy football",
            "adventure capitalist",
            "ubereats",
            "kika keyboard",
            "twitter",
            "episode",
            "tinder",
            "groupon",
            "color photo gallery",
            "hi keyboard",
            "deep clean",
            "cash app",
            "castle clash",
            "zedge",
            "virus cleaner",
            "despicable me",
            "space frontier",
            "cooking fever",
            "mcdonald",
            "hurricane tracker",
            "google photos",
            "ebay",
            "mercari",
            "geometry dash lite",
            "toy blast",
            "google translate",
            "solitaire",
            "poshmark",
            "little alchemy two",
            "paypal",
            "live",
            "rolling sky",
            "clash royale",
            "love nikki",
            "power clean",
            "candy crush saga",
            "pok",
            "iheartradio free music",
            "venmo",
            "chick",
            "gardenscapes",
            "yahoo mail",
            "free mpthree music download player",
            "pof free dating app",
            "piano tiles two",
            "fast cleaner",
            "yelp",
            "droid security",
            "free music",
            "messenger",
            "family dollar",
            "pac",
            "hbo now",
            "my talking tom",
            "flip diving",
            "word shuffle",
            "temple run two",
            "pocket mortys",
            "cheetah keyboard",
            "google home",
            "kik",
            "roller skating girls",
            "go keyboard pro",
            "photo editor",
            "color switch",
            "skype",
            "word crumble",
            "bible",
            "tap tap dash",
            "target",
            "hill climb racing two",
            "hungry shark evolution",
            "discord",
            "z camera",
            "food delivery by doordash",
            "super cleaner",
            "wheel of fortune free play",
            "ninenine arrows",
            "extreme car driving simulator",
            "credit karma",
            "dancing line",
            "facemoji emoji keyboard",
            "samsung smart switch mobile",
            "google earth",
            "rider",
            "hooked",
            "taps to riches",
            "microsoft outlook",
            "microsoft word",
            "fruit ninja",
            "sonic the hedgehog",
            "bingo party",
            "cats",
            "pixel gun threed",
            "lords mobile",
            "army men strike",
            "roku",
            "go launcher",
            "flipp",
            "virus cleaner twozerooneseven",
            "clash of clans",
            "shazam",
            "pictoword",
            "sing",
            "uber driver",
            "google docs",
            "icy ropes",
            "lucktastic",
            "fema",
            "my talking angela",
            "merge dragons",
            "real estate",
            "bubble witch three saga",
            "candy crush soda saga",
            "angry birds two",
            "fidget spinner",
            "storm radar with noaa weath",
            "dollar general",
            "jetpack joyride",
            "paper",
            "youtube kids",
            "super cleaner",
            "imo free video calls and chat",
            "bike race free",
            "text free",
            "ace cleaner",
            "tumblr",
            "watchespn",
            "sniper threed gun shooter",
            "dumb ways to die original",
            "duolingo",
            "kodi",
            "nba live mobile basketball",
            "sure universal smart tv remote",
            "zombie frontier three",
            "star wars",
            "pou",
            "sonic dash",
            "tophatter",
            "amazon alexa",
            "design home",
            "snoopy pop",
            "the floor is lava",
            "plants vs",
            "family feud",
            "free mpthree music download player",
            "layout from instagram",
            "postmates",
            "apple music",
            "rocket cleaner",
            "max craft",
            "audiobooks from audible",
            "dominoes the best domino game",
            "the sims",
            "zoosk dating app",
            "fresh ebt",
            "two for two",
            "firefox browser fast",
            "temple run",
            "tunein radio",
            "reddit",
            "groupme",
            "geometry dash world",
            "audiomack",
            "family zoo",
            "magic piano by smule",
            "sniper special blood killer",
            "family locator",
            "bounzy",
            "wayfair",
            "indeed job search",
            "gymnastics superstar",
            "outlet",
            "xfinity stream",
            "angry birds",
            "youcam makeup",
            "crossy road"
    };
}
